<a href="https://colab.research.google.com/github/07vikramsingh/numpy-ipynb/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# creating an array
a = np.array([8,7,6,5,4,4,3,2,1])

a

array([8, 7, 6, 5, 4, 4, 3, 2, 1])

In [ ]:
# access individual element in the array

a[3]


5

In [ ]:
# accesing the elemnt on particul index
a[5] =9
a

array([8, 7, 6, 5, 4, 9, 3, 2, 1])

In [ ]:
# slicing the array
a[:4]

array([8, 7, 6, 5])

In [ ]:
b = a[4:]
b
b[1] =12
a

array([ 8,  7,  6,  5,  4, 12,  3,  2,  1])

In [ ]:
# Two- and higher-dimensional arrays can be initialized from nested Python sequences
a =np.array([[1,2,3,4],[5,6,7,8],[9,0,3,4]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 3, 4]])

In [ ]:
a[2,3]

4

In [ ]:
# checking the diminsion of array
a.ndim

2

In [ ]:
# checking the shape of array
a.shape

(3, 4)

In [ ]:
# checking the  lenght shape and diminsion

len(a.shape) == a.ndim

True

In [ ]:
#  total number of elements in array is contained in the size attribute.
a.size

12

In [ ]:
import math
a.size == math.prod(a.shape)

True

In [ ]:
# chrking the data type
a.dtype

dtype('int64')

In [ ]:
# How to create a basic array
# creating an array from a sequence of elements, you can easily create an array filled with
a =np.zeros(4)
a

array([0., 0., 0., 0.])

In [ ]:
# Or an array filled with 1’s:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# Create an empty array with 2 elements
np.empty(3)

array([0. , 0.5, 1. ])

In [ ]:
# You can create an array with a range of elements

np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
# specfing the data type
np.ones(3,'int64')

array([1, 1, 1])

# Adding, **removing**, and **sorting** *elements*









In [ ]:
# sorting an array elements
a = np.array([5,3,5,7,9,2,3,1])
np.sort(a)

array([1, 2, 3, 3, 5, 5, 7, 9])

In [ ]:
# adding to array
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((b,a))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [ ]:
a = np.array([[3,4],[1,2]])
b = np.array([[6,7],[9,10]])
np.concatenate((a,b) , axis= 1)

array([[ 3,  4,  6,  7],
       [ 1,  2,  9, 10]])

In [ ]:
# How do you know the shape and size of an array?
a=np.array([[[1,2,4,2],
           [3,6,7,8]],

           [[5,6,7,3],
            [6,5,2,6]],

           [[4,6,2,7],
            [9,7,5,1]]])
a.shape

(3, 2, 4)

In [ ]:
a.ndim

3

In [ ]:
a.size

24

**Can you reshape an array?**



In [ ]:
a = np.array([1,2,3,4,5,6])
a
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# indexing and slicing

data = np.array([9,5,6,7])
a = data[3]
b = data[:3]
c = data[1:3]
print(a)
print(b)
print(c)

7
[9 5 6]
[5 6]


In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a =(a[a<6])
a

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a =(a[a>6])
a

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
# You can select elements that are divisible by 2:
div = a[a % 2 == 0]
div

array([ 8, 10, 12])

In [ ]:
c = a[(a > 2) & (a < 11)]
c

array([ 7,  8,  9, 10])